### ISSUE TITLE
Bug: Typing effect banner makes usage hard on mobile

### ISSUE THREAD

**Issue by davmillar** [GeorgeSG/sub.rehab#16]
When attempting to use the site on a mobile device, the typing effect banner causes the page to jump constantly due to the text wrapping to new lines as it fills up. This leads to difficulty pinpointing the correct links and tapping them as they become moving targets.

Recommend removing it entirely; alternately hide it on mobile; third alternative would be containing the size so the page doesn’t move when the typing occurs.

**Comment by GeorgeSG** [comment]
Hi @davmillar! Thanks for submitting a bug and apologies for the issues you're having!

Do you mind sharing a bit more information about the device and browser you're using to reproduce this?

I'd be interested to know any of:
- Device model and/or Screen resolution
- Browser (with version)

Thanks!

**Comment by GeorgeSG** [comment]
@davmillar I just deployed a couple of improvements for devices with smaller screen size. I am disabling the typing effect below screen size of 360px.

Let me know if this fixes your problem!
