### ISSUE TITLE
Change submitted URL

### ISSUE THREAD

**Issue by rajtilakjee** [GeorgeSG/sub.rehab#17]
Hey George,

First of all, great work! And kudos to you for making it open-source. Now I already submitted links to our new habitat, however, mistakenly I submitted the lengthier and incorrect invite link to our Discord server. Here are the details:

Sub: r/IndiaSocial
Incorrect link: https://discord.com/invite/r-indiasocial-727016164215226450
Correct link: https://discord.gg/gUMHDU4YGk

Let me know if I need to open a PR, would gladly do the same.

Thanks,
Rajtilak Bhattacharjee
u/UnemployedTechie2021

**Comment by GeorgeSG** [comment]
Fixed, thank you!
