### ISSUE TITLE
[Feature Request] let us input our home instance at the top of the page, and make the links all point to federated versions of lemmy/kbin

### ISSUE THREAD

**Issue by RheingoldRiver** [GeorgeSG/sub.rehab#18]
e.g. my account is on kbin.social. If I click on https://lemmy.ml/c/hamradio I would rather be pointed to https://kbin.social/m/hamradio@lemmy.ml, which I think is possible to generate procedurally based on the home instance entered by the user.

Thanks so much, this tool is already amazing!!

**Comment by GeorgeSG** [comment]
Hi @RheingoldRiver! 

This already exists as a feature. Go to "Settings" (button on the top right) and setup a Home Instance.

**Comment by RheingoldRiver** [comment]
ohhhhhh cool! I did that just now, and it seems to be working! thanks so much!
