### ISSUE TITLE
Add a link to subreddits.json

### ISSUE THREAD

**Issue by SuperCuber** [GeorgeSG/sub.rehab#19]
Would be nice to have a link on the page to the most up-to-date `subreddits.json` file, maybe even just this link `https://raw.githubusercontent.com/GeorgeSG/sub.rehab/master/data/subreddits.json`

This is helpful for accessing the data programmatically, for example I'm going to intersect my subreddit list with this :)

Thanks for the great work!

**Comment by GeorgeSG** [comment]
Thanks for the suggestion @SuperCuber!

I have added a link to the `subreddits.json` file in the FAQ section:
<img width="1010" alt="image" src="https://github.com/GeorgeSG/sub.rehab/assets/2514425/a466c3b0-aaf2-4bc2-9627-79687d70a736">

As far as intersecting it with your subreddit list - you can also import your subreddits as sub.rehab favorites from the Settings menu:
<img width="427" alt="image" src="https://github.com/GeorgeSG/sub.rehab/assets/2514425/34c75568-72e3-4009-9c06-9b11ac3ac7d2">

This will make your subscribed subreddits appear on top of the sub.rehab list :)

**Comment by SuperCuber** [comment]
Did not notice the import from reddit button (or the `reddit.com/reddits` way), thanks a lot :D

I was copying html elements from devtools and doing regex on it 😫
