### ISSUE TITLE
Linkable filters

### ISSUE THREAD

**Issue by maltfield** [GeorgeSG/sub.rehab#4]
This issue is a feature request to define the filters in either the [query string](https://en.wikipedia.org/wiki/Query_string) or [URI fragment](https://en.wikipedia.org/wiki/URI_fragment) when-clicked, such that users can copy-and-paste the URL from the address bar of their browser, share it with a friend, and their friend will see the same filters as they say on-load.

### Why?

Some folks may just want to see all of the relevant alternatives on one platform, such as lemmy

### Solution

For example, if someone clicks the "X" on Discord, the URL could change to either

 * https://https://sub.rehab/?filter=lemmy,kbin,misc,matrix or
 * https://https://sub.rehab/?#filter=lemmy,kbin,misc,matrix

Further, after clicking the "x" on kbin & matrix & misc, the URL could change to 

 * https://https://sub.rehab/?filter=lemmy or
 * https://https://sub.rehab/?#filter=lemmy

And, of course, if someone loads the URL with the filters defined above, the website should automatically adjust the filters, as desired.

Bonus: A similar variable for dark/light mode could also be added to the URI

**Comment by GeorgeSG** [comment]
Thank you for the suggestion and I completely agree! I'll implement it when I get the time. In the meantime, if someone wants to take this - PRs are welcome

**Comment by GeorgeSG** [comment]
Done, in a way. I started storing all filters in the URL. It's a bit verbose, but it works, and you can bookmark or share a URL with any filters applied. Thanks for the suggestion!
